export const STRINGS = {
  appName: 'ADOS Docs',
  subtitle: 'Documentos y cotizaciones',
  navInicio: 'Inicio',
  navClientes: 'Clientes',
  navAjustes: 'Ajustes',

  // Autenticación
  authTitle: 'Iniciar sesión',
  authRegisterTitle: 'Crear cuenta',
  authEmail: 'Correo electrónico',
  authPassword: 'Contraseña',
  authLogin: 'Iniciar sesión',
  authRegister: 'Crear cuenta',
  authLogout: 'Cerrar sesión',
  authToRegister: '¿No tienes cuenta? Crea una',
  authToLogin: '¿Ya tienes cuenta? Inicia sesión',
  authError: 'No se pudo completar la operación: ',
  authInvalidEmail: 'Ingresa un correo válido.',
  authWeakPassword: 'La contraseña debe tener al menos 6 caracteres.',
  authEmailInUse: 'El correo ya está registrado.',
  authWrongPassword: 'Correo o contraseña incorrectos.',
  authUserNotFound: 'No existe una cuenta con ese correo.',
  authRequiredField: 'Este campo es obligatorio.',
  firebaseMissingConfig: 'Falta la configuración de Firebase. Revisa .env.local.',

  // Mi perfil
  profileTitle: 'Mi perfil',
  profileName: 'Nombre mostrado',
  profilePhone: 'Teléfono',
  profileSaved: 'Perfil guardado.',

  // Perfiles emisores
  issuersTitle: 'Perfiles emisores',
  issuersEmpty: 'Aún no hay perfiles emisores. Crea el primero.',
  issuerNewTitle: 'Nuevo perfil emisor',
  issuerEditTitle: 'Editar perfil emisor',
  issuerName: 'Nombre o razón social',
  issuerKind: 'Tipo de emisor',
  issuerKindEmpresa: 'Empresa',
  issuerKindPersona: 'Persona natural',
  issuerRut: 'RUT',
  issuerPhone: 'Teléfono',
  issuerEmail: 'Correo',
  issuerAddress: 'Dirección',
  issuerLogo: 'Logo',
  issuerInfo: 'Información adicional',
  issuerGiro: 'Giro',
  issuerSignature: 'Firma',
  issuerSignatureHint: 'Imagen de la firma (PNG, JPG o WebP).',
  issuerSignaturePick: 'Subir firma',
  issuerSignatureRemove: 'Quitar firma',
  issuerSignatureInvalid: 'El archivo no es una imagen válida o supera el tamaño máximo (1 MB).',
  signerName: 'Nombre del firmante',
  signerRut: 'RUT del firmante',
  signerRole: 'Cargo del firmante',
  issuerDefault: 'Predeterminado',
  issuerSetDefault: 'Definir como predeterminado',
  issuerSave: 'Guardar perfil emisor',
  issuerSaved: 'Perfil emisor guardado.',
  issuerDeleted: 'Perfil emisor eliminado.',
  issuerConfirmDelete: '¿Eliminar este perfil emisor? Las cotizaciones que lo usaron conservarán sus datos.',
  issuerNew: 'Nuevo perfil emisor',
  issuerPreviewPdf: 'Generar PDF de prueba',
  issuerPreviewTitle: 'Vista previa del documento',
  issuerPreviewResumido: 'PDF resumido',
  issuerPreviewDetallado: 'PDF detallado',
  usarEmisor: 'Usar como emisor de esta cotización',
  refreshIssuer: 'Actualizar datos del emisor',
  refreshIssuerDone: 'Datos del emisor actualizados.',
  refreshIssuerNoProfile: 'El perfil emisor original ya no está disponible.',

  nuevoCotizacion: 'Nueva cotización',
  historialVacio: 'Aún no hay cotizaciones. Toca "Nueva cotización" para empezar.',
  cotizacionesActivas: 'Cotizaciones activas',
  cotizacionesArchivadas: 'Archivadas',
  archivadasVacio: 'Aún no hay cotizaciones archivadas.',
  borrador: 'Borrador',
  estado: 'Estado',
  emisor: 'Emisor',

  statusPendiente: 'Pendiente',
  statusSeRealizara: 'Se realizará',
  statusNoRealizada: 'No realizada',
  cambiarEstado: 'Cambiar estado',
  cambiarEstadoTitle: 'Cambiar estado de la cotización',
  estadoCambiado: 'Estado actualizado.',

  creditElaboradaPor: '',
  creditExportadoPor: 'Exportado por ADOS DOCS',

  configTitle: 'Configuración de la empresa',
  configName: 'Nombre',
  configRut: 'RUT',
  configPhone: 'Teléfono',
  configEmail: 'Correo',
  configAddress: 'Dirección',
  configLogo: 'Logo',
  configLogoHint: 'Imagen PNG, JPG o WebP de hasta 1 MB.',
  configSave: 'Guardar configuración',
  configSaved: 'Configuración guardada.',
  configLogoInvalid: 'El archivo no es una imagen válida o supera el tamaño máximo (1 MB).',
  themeSectionTitle: 'Apariencia',
  themeColorLabel: 'Color del tema',
  rutInvalid: 'El RUT ingresado no es válido.',
  navCatalogo: 'Catálogo',
  catalogTitle: 'Catálogo de ítems',
  catalogEmpty: 'Aún no hay ítems en el catálogo. Crea el primero.',
  catalogNew: 'Nuevo ítem',
  catalogEdit: 'Editar',
  catalogFormNew: 'Guardar ítem',
  catalogFormEdit: 'Guardar cambios',
  catalogDelete: 'Eliminar',
  catalogConfirmDelete: '¿Eliminar este ítem del catálogo?',
  catalogSaved: 'Ítem guardado en el catálogo.',
  catalogDeleted: 'Ítem eliminado del catálogo.',
  catalogName: 'Nombre',
  catalogDescription: 'Descripción (opcional)',
  catalogCategory: 'Categoría',
  catalogUnit: 'Unidad',
  catalogPrice: 'Precio unitario',
  catalogSearch: 'Buscar ítems...',
  catalogCategoryAll: 'Todas',
  catalogCatManoDeObra: 'Mano de obra',
  catalogCatMaterial: 'Material',
  catalogCatServicio: 'Servicio',
  catalogCatOtro: 'Otro',
  catalogSaveFromItem: 'Guardar en catálogo',
  catalogSaveTitle: 'Guardar en catálogo',
  cambiarLogo: 'Cambiar logo',
  quitarLogo: 'Quitar logo',

  clientesTitle: 'Clientes',
  clientesVacio: 'Aún no hay clientes. Crea el primero.',
  nuevoCliente: 'Nuevo cliente',
  editarCliente: 'Editar cliente',
  clienteName: 'Nombre',
  clienteRut: 'RUT (opcional)',
  clientePhone: 'Teléfono (opcional)',
  clienteAddress: 'Dirección (opcional)',
  guardarCliente: 'Guardar cliente',
  clienteSaved: 'Cliente guardado.',
  eliminarCliente: 'Eliminar',
  confirmEliminarCliente: '¿Eliminar a este cliente? Las cotizaciones guardadas conservarán sus datos.',
  buscarCliente: 'Buscar cliente...',

  budgetTitle: 'Cotización',
  budgetNumber: 'Número',
  budgetDate: 'Fecha',
  budgetClient: 'Cliente',
  sinCliente: 'Sin cliente',
  budgetJobName: 'Nombre de la obra',
  budgetJobAddress: 'Dirección de la obra',
  budgetPaymentTerms: 'Forma de pago',
  budgetPaymentCustom: 'Escribe la forma de pago',
  paymentOption: 'Selecciona forma de pago',
  paymentCustom: 'Personalizado',
  budgetValidity: 'Vigencia cotización',
  budgetExecutionTime: 'Tiempo estimado de ejecución',
  budgetNotes: 'Observaciones',
  budgetDiscount: 'Descuento ($)',
  budgetIva: 'IVA (%)',
  budgetSections: 'Secciones / Especialidades',
  sectionsEmpty: 'Aún no hay secciones. Agrega la primera.',
  addSection: 'Agregar sección',
  newSectionTitle: 'Nueva sección',
  editSectionTitle: 'Editar sección',
  sectionNameLabel: 'Nombre de la sección',
  guardarSeccion: 'Guardar sección',
  crearSeccion: 'Crear sección',
  sectionSuggestTitle: 'Sugerencias rápidas',
  sectionSubtotal: 'Subtotal de sección',
  sectionEmptyItems: 'Sin ítems todavía.',
  sectionWorkDetails: 'Detalle de trabajos',
  sectionAddWork: 'Agregar trabajo',
  sectionWorkPlaceholder: 'Descripción del trabajo',
  sectionGlobalAmount: 'Valor global',
  sectionGlobalLabel: 'Etiqueta (opcional)',
  addItem: 'Agregar ítem',
  eliminarSeccion: 'Eliminar sección',
  confirmEliminarSeccion: '¿Eliminar esta sección y todos sus ítems?',
  itemDescription: 'Descripción',
  itemType: 'Tipo',
  itemQuantity: 'Cantidad',
  itemUnit: 'Unidad',
  itemUnitPrice: 'Precio unitario',
  itemMonto: 'Monto',
  guardarItem: 'Guardar ítem',
  nuevoItemTitle: 'Nuevo ítem',
  editItemTitle: 'Editar ítem',
  cancelarItem: 'Cancelar',
  subtotalLabel: 'Subtotal',
  descuentoLabel: 'Descuento',
  baseImponibleLabel: 'Base imponible',
  ivaLabel: 'IVA',
  totalLabel: 'TOTAL',
  totalCotizacion: 'TOTAL COTIZACIÓN',
  verDetalle: 'Ver detalle',
  ocultarDetalle: 'Ocultar detalle',

  firmaLabel: 'Firma',
  firmaSinFirma: 'Sin firma',
  firmaManual: 'Espacio para firma manual',
  firmaGuardada: 'Firma guardada del emisor',
  guardarCotizacion: 'Guardar cotización',
  guardarBorrador: 'Guardar como borrador',
  budgetSaved: 'Cotización guardada.',
  budgetDraftSaved: 'Borrador guardado.',
  budgetNoClienteLast: 'El cliente elegido ya no está en el listado.',
  guardarSinCliente: 'Para guardar como cotización debes seleccionar un cliente y agregar ítems válidos. ¿Guardar como borrador?',

  inicioTitle: 'Mis cotizaciones',
  abrirEditar: 'Abrir / Editar',
  duplicar: 'Duplicar',
  compartir: 'Compartir',
  descargarDetallado: 'Descargar PDF detallado',
  descargarResumido: 'Descargar PDF resumido',
  eliminar: 'Eliminar',
  confirmEliminarCotizacion: '¿Eliminar esta cotización? Esta acción no se puede deshacer.',
  confirmDiscardUnsaved: '¿Descartar cambios sin guardar?',
  duplicated: 'Cotización duplicada.',
  eliminado: 'Cotización eliminada.',

  shareText: 'Cotización N.º {num}',
  shareErrTitle: 'Error al compartir',
  shareFailed: 'No se pudo compartir la cotización.',
  pdfBlocked: 'No se puede generar el PDF: {reason}',

  confirm: 'Aceptar',
  cancel: 'Cancelar',
  goBack: 'Volver',
  emptyLabel: '—',
} as const

export const PAYMENT_PRESETS: readonly string[] = [
  '100% al finalizar',
  '50% al inicio / 50% al finalizar',
  '40% / 30% / 30%',
  '30% anticipo / 70% al finalizar',
  'Por avance de obra',
]

export const PAYMENT_CUSTOM_VALUE = 'custom'

export const SECTION_SUGGESTIONS: readonly string[] = [
  'Obra general',
  'Electricidad',
  'Gasfitería',
  'Soldadura',
  'Pintura',
  'Carpintería',
  'Techumbre',
  'Terminaciones',
  'Otro',
]

export type StringKey = keyof typeof STRINGS
